version: '3.8'

services:
  input-sys:
    image: input-sys:v1.0
    ports:
      - "6002:6000"
  dev-sys:
    image: dev-sys:v1.0
    ports:
      - "6000:6000"
    stdin_open: true 
    tty: true
  ingestion-sys:
    image: ingestion-sys:v1.0
    ports:
      - "6003:4000"
  prep-sys:
    image: prep-sys:v1.0
    ports:
      - "6004:5000"
  seg-sys:
    image: seg-sys:v1.0
    ports:
      - "6005:6000"
    stdin_open: true 
    tty: true
  prod-sys:
    image: prod-sys:v1.0
    ports:
      - "6001:6000"
  #orch-sys:
  #  image: orch-sys:v1.0
  #  ports:
  #    - "6001:6000"
